- hosts: all
  become: yes

  roles:
    - geerlingguy.pip

  collections:
    - community.docker

  tasks:
    - name: install docker
      tags: prepare
      become: yes
      pip:
        name: docker
        state: present

    - name: create .env from template
      tags: prepare
      ansible.builtin.template:
        src: templates/env.j2
        dest: "{{ env_name }}"
        mode: "666"

    - name: create redmine container
      tags: deploy
      become: yes
      community.docker.docker_container:
        name: redmine
        image: redmine:5.0
        env_file: "{{ env_name }}"
        ports:
          - "{{ active_port }}:3000"
        restart_policy: always

- hosts: webservers
  become: yes
  tags: datadog

  roles:
    - datadog.datadog

  tasks:
    - name: start datadog agent
      service:
        name: datadog-agent
        state: restarted
        enabled: yes
