env_path: "~/.env"

db_host: "rc1d-fl5r68kld42jbrv4.mdb.yandexcloud.net"
db_port: "6432"
db_name: "redmine"
db_user: "ilya"

# datadog
datadog_agent_flavor: "datadog-agent"
datadog_api_key: "{{ dd_api_key}}"
datadog_site: "datadoghq.eu"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Redmine
        url: http://0.0.0.0
        timeout: 5
        tags:
          - redmine
        collect_response_time: true
